### ISSUE TITLE
CSV parser library to work with line-by-line

### ISSUE THREAD

**Issue by ebezerra-it** [paya-cz/line-by-line#1]
Hi there, mate!
You did an amazing job here! I was struggled with reading huge CSV files into DB because I need to perform some prior data sync transformation. And after some hours looking for a library that supports sync stream loading, I found yours. 👊

May you please recommend a csv to json parser library in order to parse each string row into my typed JSON?

Thanks again and let me know if you need some help with your library. I would be happy to contribute.

Kind regards,
Eduardo

**Comment by paya-cz** [comment]
thank you for your kind words about my package. 

I needed to do exactly what you are looking for as well. I had great success with csv-parse

https://csv.js.org/parse/
